### PR TITLE
Initialize project with components

### PR DESCRIPTION
**Pull request by djo1975**
- I set up client-side routing using [React Router V6].
-I Set up a new React application using [Create React App]
-I Created a directory for your reusable /components.
-I added two <Route> to my application:
/books - the default view:
-Displaying a list of books
-Displaying a form for adding a book (no functionality yet).
/categories:
-Displaying a button "Check status" only.
-Created a <Navbar> component that includes <Link>s to the two routes you created
-Created a <Book> component that displays a single book (props are title and author.
-Each Book has a "remove" button (no functionality yet)
-Created a <Form> component with inputs for a title and an author.
Note: Styling is NOT required at this state

### CODE REVIEW

**Review by danmainah — CHANGES_REQUESTED** [review]
Hi  @djo1975 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter failing, kindly fix the errors and ensure all linter checks are passing 
image



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by djo1975** [comment]
Hi @danmainah
Thank you for the suggestion. The issue was that I did not have any styling at all. I have learned that pull requests cannot be submitted without any styling. Thank you again, and I am confident that everything is now as required by the task.

**Review by alexander16108 — APPROVED** [review]
Hi @djo1975 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights

✅ Great use of Git flow. 💯
✅ Your project is documented professionally. 📜
✅ Descriptive PR title, summary and commit messages. 💬

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by djo1975** [comment]
Hi @alexander16108 
THX :)

**Comment by alexander16108** [comment]
@djo1975 UR WELCOME

**Pull request merged**
